[package]
name = "some_platformer_client"
version = "0.1.0"
authors = ["Gregory Obanos <gregory.obanos@gmail.com>", "Olivier Pinon <oliv.pinon@gmail.com"]

[dependencies]
ggez = "0.4.2"
log = "0.4.1"
flexi_logger = "0.8.1"

some_platformer_lib = { path = "../lib" }